"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {}

setup(
    name="VAJEH",
    version="1.0.0",
    description= "VAJEH Offline EN-FA dictionary with about 80,000 words",
    long_description="Offline EN-FA dictionary with around 80,000 words by Amirhossein Khosravi\nwww.amirkho.ir\ngithub.com/amirkho-py/vajeh",
    author="Amirhossein Khosravi",
    author_email="me@amirkho.ir",
    license="MIT",
    url="https://github.com/amirkho-py/vajeh",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],

    
)

